spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shortening-url
    username: sa
    password:
    dirver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use_sql_comments: true
    properties:   
      hibernate:
        # show_sql: true :> show_sql : 옵션은 System.out 에 하이버네이트 실행 SQL을 남긴다. 모든 로그출력은 가급적 로거에 남겨야 한다.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.SQL : 옵션은 