spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shortening-url
    username: sa
    password:
    dirver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use_sql_comments: true
    properties:   
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug